require: rubocop-jekyll

inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.0.0
  Include:
    - lib/**/*.rb

  Exclude:
    - .gitignore
    - .rspec
    - .rubocop.yml
    - .travis.yml

    - Gemfile.lock
    - History.markdown
    - LICENSE.txt
    - README.md

    - script/**/*
    - vendor/**/*

Naming/MemoizedInstanceVariableName:
  Exclude:
    - lib/jekyll-feed/page-without-a-file.rb
