language: ruby
cache: bundler
dist: focal

rvm:
  - 3.0
  - 2.7
  - 2.5

branches:
  only:
    - main

env:
  matrix:
    - JEKYLL_VERSION="~> 3.9"
    - JEKYLL_VERSION="~> 4.2"

matrix:
  exclude:
    - rvm: 2.5
      env: JEKYLL_VERSION="~> 4.2"

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - bundle update

script:
  - script/cibuild
