language: ruby
cache: bundler
rvm:
  - &latest_ruby 2.7
  - 2.5

branches:
  only:
  - main

env:
  matrix:
    - JEKYLL_VERSION="~> 3.9"
    - JEKYLL_VERSION="~> 4.0"

matrix:
  include:
    - rvm: *latest_ruby
      env: JEKYLL_VERSION="~> 3.9"
    - rvm: *latest_ruby
      env: JEKYLL_VERSION="~> 4.2"

before_install:
  - gem update --system
  - gem install bundler

before_script: bundle update
script: script/cibuild
