language: ruby
cache: bundler
rvm:
  - &latest_ruby 2.7
  - 2.5

branches:
  only:
  - main

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - JEKYLL_VERSION="~> 3.9"
    - JEKYLL_VERSION="~> 4.0"

matrix:
  include:
    - rvm: *latest_ruby
      env: JEKYLL_VERSION="~> 3.8.6"
    - rvm: *latest_ruby
      env: JEKYLL_VERSION=">= 4.0.0"

before_install:
  - gem update --system
  - gem install bundler

before_script: bundle update
script: script/cibuild
